// <auto-generated />
use crate::delegate_loader::{AssemblyDelegateLoader, MethodWithUnknownSignature};
use crate::error::Error;
use crate::loader::get_assembly_delegate_loader;
use crate::pdcstr;
use crate::pdcstring::{PdCStr, PdCString};

pub type PowerShellHandle = *mut libc::c_void;

pub type FnPowerShellCreate = unsafe extern "system" fn() -> PowerShellHandle;

pub type FnPowerShellAddArgumentString = unsafe extern "system" fn(handle: PowerShellHandle, argument: *const libc::c_char);

pub type FnPowerShellAddParameterString = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: *const libc::c_char);

pub type FnPowerShellAddParameterInt = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: i32);

pub type FnPowerShellAddParameterLong = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: i64);

pub type FnPowerShellAddCommand = unsafe extern "system" fn(handle: PowerShellHandle, command: *const libc::c_char);

pub type FnPowerShellAddScript = unsafe extern "system" fn(handle: PowerShellHandle, script: *const libc::c_char);

pub type FnPowerShellAddStatement = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellInvoke = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellClear = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellExportToXml = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnPowerShellExportToJson = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnPowerShellExportToString = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnMarshalFreeCoTaskMem = unsafe extern "system" fn(ptr: *mut libc::c_void);

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ApiPs74 {
    pub create_fn: *const libc::c_void,
    pub add_argument_string_fn: *const libc::c_void,
    pub add_parameter_string_fn: *const libc::c_void,
    pub add_parameter_int_fn: *const libc::c_void,
    pub add_parameter_long_fn: *const libc::c_void,
    pub add_command_fn: *const libc::c_void,
    pub add_script_fn: *const libc::c_void,
    pub add_statement_fn: *const libc::c_void,
    pub invoke_fn: *const libc::c_void,
    pub clear_fn: *const libc::c_void,
    pub export_to_xml_fn: *const libc::c_void,
    pub export_to_json_fn: *const libc::c_void,
    pub export_to_string_fn: *const libc::c_void,
    pub marshal_free_co_task_mem_fn: *const libc::c_void,
}

pub type FnBindingsGetApiPs74 = unsafe extern "system" fn() -> *const ApiPs74;

pub struct Bindings {
    pub create_fn: FnPowerShellCreate,
    pub add_argument_string_fn: FnPowerShellAddArgumentString,
    pub add_parameter_string_fn: FnPowerShellAddParameterString,
    pub add_parameter_int_fn: FnPowerShellAddParameterInt,
    pub add_parameter_long_fn: FnPowerShellAddParameterLong,
    pub add_command_fn: FnPowerShellAddCommand,
    pub add_script_fn: FnPowerShellAddScript,
    pub add_statement_fn: FnPowerShellAddStatement,
    pub invoke_fn: FnPowerShellInvoke,
    pub clear_fn: FnPowerShellClear,
    pub export_to_xml_fn: FnPowerShellExportToXml,
    pub export_to_json_fn: FnPowerShellExportToJson,
    pub export_to_string_fn: FnPowerShellExportToString,
    pub marshal_free_co_task_mem_fn: FnMarshalFreeCoTaskMem,
}

impl Bindings {
    pub fn new() -> Result<Self, Error> {
        let fn_loader = get_assembly_delegate_loader();
        Self::new_with_loader(&fn_loader)
    }

    pub fn new_with_loader(fn_loader: &AssemblyDelegateLoader<PdCString>) -> Result<Self, Error> {
        fn get_function_pointer(
            fn_loader: &AssemblyDelegateLoader<PdCString>,
            type_name: impl AsRef<PdCStr>,
            method_name: impl AsRef<PdCStr>,
        ) -> Result<MethodWithUnknownSignature, Error> {
            fn_loader.get_function_pointer_for_unmanaged_callers_only_method(type_name, method_name)
        }

        let get_api_fn: FnBindingsGetApiPs74 = {
            let fn_ptr = get_function_pointer(
                fn_loader,
                pdcstr!("NativeHost.Bindings, Bindings"),
                pdcstr!("Bindings_GetApiPS74"),
            )?;
            unsafe { std::mem::transmute(fn_ptr) }
        };

        let api = unsafe {
            let api_ptr = get_api_fn();
            assert!(!api_ptr.is_null());
            *api_ptr
        };

        Ok(Self {
            create_fn: unsafe { std::mem::transmute(api.create_fn) },
            add_argument_string_fn: unsafe { std::mem::transmute(api.add_argument_string_fn) },
            add_parameter_string_fn: unsafe { std::mem::transmute(api.add_parameter_string_fn) },
            add_parameter_int_fn: unsafe { std::mem::transmute(api.add_parameter_int_fn) },
            add_parameter_long_fn: unsafe { std::mem::transmute(api.add_parameter_long_fn) },
            add_command_fn: unsafe { std::mem::transmute(api.add_command_fn) },
            add_script_fn: unsafe { std::mem::transmute(api.add_script_fn) },
            add_statement_fn: unsafe { std::mem::transmute(api.add_statement_fn) },
            invoke_fn: unsafe { std::mem::transmute(api.invoke_fn) },
            clear_fn: unsafe { std::mem::transmute(api.clear_fn) },
            export_to_xml_fn: unsafe { std::mem::transmute(api.export_to_xml_fn) },
            export_to_json_fn: unsafe { std::mem::transmute(api.export_to_json_fn) },
            export_to_string_fn: unsafe { std::mem::transmute(api.export_to_string_fn) },
            marshal_free_co_task_mem_fn: unsafe { std::mem::transmute(api.marshal_free_co_task_mem_fn) },
        })
    }
}
