// <auto-generated />
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::delegate_loader::{AssemblyDelegateLoader, MethodWithUnknownSignature};
use crate::error::Error;
use crate::loader::get_assembly_delegate_loader;
use crate::pdcstr;
use crate::pdcstring::{PdCStr, PdCString};

pub type PowerShellHandle = *mut libc::c_void;

pub type FnPowerShellCreate = unsafe extern "system" fn() -> PowerShellHandle;

pub type FnPowerShellAddArgumentString = unsafe extern "system" fn(handle: PowerShellHandle, argument: *const libc::c_char);

pub type FnPowerShellAddParameterString = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: *const libc::c_char);

pub type FnPowerShellAddParameterInt = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: i32);

pub type FnPowerShellAddParameterLong = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: i64);

pub type FnPowerShellAddCommand = unsafe extern "system" fn(handle: PowerShellHandle, command: *const libc::c_char);

pub type FnPowerShellAddScript = unsafe extern "system" fn(handle: PowerShellHandle, script: *const libc::c_char);

pub type FnPowerShellAddStatement = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellInvoke = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellClear = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellExportToXml = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnPowerShellExportToJson = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnPowerShellExportToString = unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnBindingsInvokeMemberJson = unsafe extern "system" fn(handle: PowerShellHandle, member_name: *const libc::c_char, arguments_json: *const libc::c_char) -> *const libc::c_char;

pub type FnBindingsGetPropertyJson = unsafe extern "system" fn(handle: PowerShellHandle, property_name: *const libc::c_char) -> *const libc::c_char;

pub type FnBindingsSetPropertyJson = unsafe extern "system" fn(handle: PowerShellHandle, property_name: *const libc::c_char, value_json: *const libc::c_char) -> *const libc::c_char;

pub type FnBindingsInvokeStaticMemberJson = unsafe extern "system" fn(member_name: *const libc::c_char, arguments_json: *const libc::c_char) -> *const libc::c_char;

pub type FnGCHandleFree = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnMarshalFreeCoTaskMem = unsafe extern "system" fn(ptr: *mut libc::c_void);

pub type FnPowerShell_Auto_AddCommand_String = unsafe extern "system" fn(handle: PowerShellHandle, cmdlet: *const libc::c_char) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddCommand_String_Bool = unsafe extern "system" fn(handle: PowerShellHandle, cmdlet: *const libc::c_char, useLocalScope: i32) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddParameter_String = unsafe extern "system" fn(handle: PowerShellHandle, parameterName: *const libc::c_char) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddScript_String = unsafe extern "system" fn(handle: PowerShellHandle, script: *const libc::c_char) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddScript_String_Bool = unsafe extern "system" fn(handle: PowerShellHandle, script: *const libc::c_char, useLocalScope: i32) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddStatement_NoArgs = unsafe extern "system" fn(handle: PowerShellHandle) -> PowerShellHandle;

pub type FnPowerShell_Auto_CreateNestedPowerShell_NoArgs = unsafe extern "system" fn(handle: PowerShellHandle) -> PowerShellHandle;

pub type FnPowerShell_Auto_Dispose_NoArgs = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShell_Auto_Stop_NoArgs = unsafe extern "system" fn(handle: PowerShellHandle);

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ApiPs74 {
    pub create_fn: *const libc::c_void,
    pub add_argument_string_fn: *const libc::c_void,
    pub add_parameter_string_fn: *const libc::c_void,
    pub add_parameter_int_fn: *const libc::c_void,
    pub add_parameter_long_fn: *const libc::c_void,
    pub add_command_fn: *const libc::c_void,
    pub add_script_fn: *const libc::c_void,
    pub add_statement_fn: *const libc::c_void,
    pub invoke_fn: *const libc::c_void,
    pub clear_fn: *const libc::c_void,
    pub export_to_xml_fn: *const libc::c_void,
    pub export_to_json_fn: *const libc::c_void,
    pub export_to_string_fn: *const libc::c_void,
    pub invoke_member_json_fn: *const libc::c_void,
    pub get_property_json_fn: *const libc::c_void,
    pub set_property_json_fn: *const libc::c_void,
    pub invoke_static_member_json_fn: *const libc::c_void,
    pub gc_handle_free_fn: *const libc::c_void,
    pub marshal_free_co_task_mem_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_co_mm_a_n_d_s_tr_i_n_g_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_co_mm_a_n_d_s_tr_i_n_g_b_o_o_l_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_pa_ra_me_t_e_r_s_tr_i_n_g_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_sc_ri_p_t_s_tr_i_n_g_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_sc_ri_p_t_s_tr_i_n_g_b_o_o_l_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_st_at_em_e_n_t_n_oa_r_g_s_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_c_re_at_en_es_te_dp_ow_er_sh_e_l_l_n_oa_r_g_s_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_d_is_po_s_e_n_oa_r_g_s_fn: *const libc::c_void,
    pub p_ow_er_sh_e_l_l_a_u_t_o_s_t_o_p_n_oa_r_g_s_fn: *const libc::c_void,
}

pub type FnBindingsGetApiPs74 = unsafe extern "system" fn() -> *const ApiPs74;

pub struct Bindings {
    pub create_fn: FnPowerShellCreate,
    pub add_argument_string_fn: FnPowerShellAddArgumentString,
    pub add_parameter_string_fn: FnPowerShellAddParameterString,
    pub add_parameter_int_fn: FnPowerShellAddParameterInt,
    pub add_parameter_long_fn: FnPowerShellAddParameterLong,
    pub add_command_fn: FnPowerShellAddCommand,
    pub add_script_fn: FnPowerShellAddScript,
    pub add_statement_fn: FnPowerShellAddStatement,
    pub invoke_fn: FnPowerShellInvoke,
    pub clear_fn: FnPowerShellClear,
    pub export_to_xml_fn: FnPowerShellExportToXml,
    pub export_to_json_fn: FnPowerShellExportToJson,
    pub export_to_string_fn: FnPowerShellExportToString,
    pub invoke_member_json_fn: FnBindingsInvokeMemberJson,
    pub get_property_json_fn: FnBindingsGetPropertyJson,
    pub set_property_json_fn: FnBindingsSetPropertyJson,
    pub invoke_static_member_json_fn: FnBindingsInvokeStaticMemberJson,
    pub gc_handle_free_fn: FnGCHandleFree,
    pub marshal_free_co_task_mem_fn: FnMarshalFreeCoTaskMem,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_co_mm_a_n_d_s_tr_i_n_g_fn: FnPowerShell_Auto_AddCommand_String,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_co_mm_a_n_d_s_tr_i_n_g_b_o_o_l_fn: FnPowerShell_Auto_AddCommand_String_Bool,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_pa_ra_me_t_e_r_s_tr_i_n_g_fn: FnPowerShell_Auto_AddParameter_String,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_sc_ri_p_t_s_tr_i_n_g_fn: FnPowerShell_Auto_AddScript_String,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_sc_ri_p_t_s_tr_i_n_g_b_o_o_l_fn: FnPowerShell_Auto_AddScript_String_Bool,
    pub p_ow_er_sh_e_l_l_a_u_t_o_a_dd_st_at_em_e_n_t_n_oa_r_g_s_fn: FnPowerShell_Auto_AddStatement_NoArgs,
    pub p_ow_er_sh_e_l_l_a_u_t_o_c_re_at_en_es_te_dp_ow_er_sh_e_l_l_n_oa_r_g_s_fn: FnPowerShell_Auto_CreateNestedPowerShell_NoArgs,
    pub p_ow_er_sh_e_l_l_a_u_t_o_d_is_po_s_e_n_oa_r_g_s_fn: FnPowerShell_Auto_Dispose_NoArgs,
    pub p_ow_er_sh_e_l_l_a_u_t_o_s_t_o_p_n_oa_r_g_s_fn: FnPowerShell_Auto_Stop_NoArgs,
}

impl Bindings {
    pub fn new() -> Result<Self, Error> {
        let fn_loader = get_assembly_delegate_loader();
        Self::new_with_loader(&fn_loader)
    }

    pub fn new_with_loader(fn_loader: &AssemblyDelegateLoader<PdCString>) -> Result<Self, Error> {
        fn get_function_pointer(
            fn_loader: &AssemblyDelegateLoader<PdCString>,
            type_name: impl AsRef<PdCStr>,
            method_name: impl AsRef<PdCStr>,
        ) -> Result<MethodWithUnknownSignature, Error> {
            fn_loader.get_function_pointer_for_unmanaged_callers_only_method(type_name, method_name)
        }

        let get_api_fn: FnBindingsGetApiPs74 = {
            let fn_ptr = get_function_pointer(
                fn_loader,
                pdcstr!("NativeHost.Bindings, Bindings"),
                pdcstr!("Bindings_GetApiPS74"),
            )?;
            unsafe { std::mem::transmute(fn_ptr) }
        };

        let api = unsafe {
            let api_ptr = get_api_fn();
            assert!(!api_ptr.is_null());
            *api_ptr
        };

        Ok(Self {
            create_fn: unsafe { std::mem::transmute(api.create_fn) },
            add_argument_string_fn: unsafe { std::mem::transmute(api.add_argument_string_fn) },
            add_parameter_string_fn: unsafe { std::mem::transmute(api.add_parameter_string_fn) },
            add_parameter_int_fn: unsafe { std::mem::transmute(api.add_parameter_int_fn) },
            add_parameter_long_fn: unsafe { std::mem::transmute(api.add_parameter_long_fn) },
            add_command_fn: unsafe { std::mem::transmute(api.add_command_fn) },
            add_script_fn: unsafe { std::mem::transmute(api.add_script_fn) },
            add_statement_fn: unsafe { std::mem::transmute(api.add_statement_fn) },
            invoke_fn: unsafe { std::mem::transmute(api.invoke_fn) },
            clear_fn: unsafe { std::mem::transmute(api.clear_fn) },
            export_to_xml_fn: unsafe { std::mem::transmute(api.export_to_xml_fn) },
            export_to_json_fn: unsafe { std::mem::transmute(api.export_to_json_fn) },
            export_to_string_fn: unsafe { std::mem::transmute(api.export_to_string_fn) },
            invoke_member_json_fn: unsafe { std::mem::transmute(api.invoke_member_json_fn) },
            get_property_json_fn: unsafe { std::mem::transmute(api.get_property_json_fn) },
            set_property_json_fn: unsafe { std::mem::transmute(api.set_property_json_fn) },
            invoke_static_member_json_fn: unsafe { std::mem::transmute(api.invoke_static_member_json_fn) },
            gc_handle_free_fn: unsafe { std::mem::transmute(api.gc_handle_free_fn) },
            marshal_free_co_task_mem_fn: unsafe { std::mem::transmute(api.marshal_free_co_task_mem_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_a_dd_co_mm_a_n_d_s_tr_i_n_g_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_a_dd_co_mm_a_n_d_s_tr_i_n_g_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_a_dd_co_mm_a_n_d_s_tr_i_n_g_b_o_o_l_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_a_dd_co_mm_a_n_d_s_tr_i_n_g_b_o_o_l_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_a_dd_pa_ra_me_t_e_r_s_tr_i_n_g_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_a_dd_pa_ra_me_t_e_r_s_tr_i_n_g_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_a_dd_sc_ri_p_t_s_tr_i_n_g_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_a_dd_sc_ri_p_t_s_tr_i_n_g_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_a_dd_sc_ri_p_t_s_tr_i_n_g_b_o_o_l_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_a_dd_sc_ri_p_t_s_tr_i_n_g_b_o_o_l_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_a_dd_st_at_em_e_n_t_n_oa_r_g_s_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_a_dd_st_at_em_e_n_t_n_oa_r_g_s_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_c_re_at_en_es_te_dp_ow_er_sh_e_l_l_n_oa_r_g_s_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_c_re_at_en_es_te_dp_ow_er_sh_e_l_l_n_oa_r_g_s_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_d_is_po_s_e_n_oa_r_g_s_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_d_is_po_s_e_n_oa_r_g_s_fn) },
            p_ow_er_sh_e_l_l_a_u_t_o_s_t_o_p_n_oa_r_g_s_fn: unsafe { std::mem::transmute(api.p_ow_er_sh_e_l_l_a_u_t_o_s_t_o_p_n_oa_r_g_s_fn) },
        })
    }
}
