// <auto-generated />
using System;
using System.Runtime.InteropServices;

namespace NativeHost
{
    public static partial class Bindings
    {
        [StructLayout(LayoutKind.Sequential)]
        private struct ApiPS74
        {
            public IntPtr PowerShell_Create;
            public IntPtr PowerShell_AddArgument_String;
            public IntPtr PowerShell_AddParameter_String;
            public IntPtr PowerShell_AddParameter_Int;
            public IntPtr PowerShell_AddParameter_Long;
            public IntPtr PowerShell_AddCommand;
            public IntPtr PowerShell_AddScript;
            public IntPtr PowerShell_AddStatement;
            public IntPtr PowerShell_Invoke;
            public IntPtr PowerShell_Clear;
            public IntPtr PowerShell_ExportToXml;
            public IntPtr PowerShell_ExportToJson;
            public IntPtr PowerShell_ExportToString;
            public IntPtr Marshal_FreeCoTaskMem;
        }

        private static readonly object ApiPS74Lock = new object();
        private static IntPtr ApiPS74Ptr = IntPtr.Zero;

        [UnmanagedCallersOnly]
        public static IntPtr Bindings_GetApiPS74()
        {
            lock (ApiPS74Lock)
            {
                if (ApiPS74Ptr == IntPtr.Zero)
                {
                    ApiPS74 api = CreateApiPS74();
                    ApiPS74Ptr = Marshal.AllocCoTaskMem(Marshal.SizeOf<ApiPS74>());
                    Marshal.StructureToPtr(api, ApiPS74Ptr, false);
                }

                return ApiPS74Ptr;
            }
        }

        private static unsafe ApiPS74 CreateApiPS74()
        {
            return new ApiPS74
            {
                PowerShell_Create = (IntPtr)(delegate* unmanaged<IntPtr>)&PowerShell_Create,
                PowerShell_AddArgument_String = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, void>)&PowerShell_AddArgument_String,
                PowerShell_AddParameter_String = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr, void>)&PowerShell_AddParameter_String,
                PowerShell_AddParameter_Int = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, int, void>)&PowerShell_AddParameter_Int,
                PowerShell_AddParameter_Long = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, long, void>)&PowerShell_AddParameter_Long,
                PowerShell_AddCommand = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, void>)&PowerShell_AddCommand,
                PowerShell_AddScript = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, void>)&PowerShell_AddScript,
                PowerShell_AddStatement = (IntPtr)(delegate* unmanaged<IntPtr, void>)&PowerShell_AddStatement,
                PowerShell_Invoke = (IntPtr)(delegate* unmanaged<IntPtr, void>)&PowerShell_Invoke,
                PowerShell_Clear = (IntPtr)(delegate* unmanaged<IntPtr, void>)&PowerShell_Clear,
                PowerShell_ExportToXml = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_ExportToXml,
                PowerShell_ExportToJson = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_ExportToJson,
                PowerShell_ExportToString = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_ExportToString,
                Marshal_FreeCoTaskMem = (IntPtr)(delegate* unmanaged<IntPtr, void>)&Marshal_FreeCoTaskMem,
            };
        }
    }
}
